### ISSUE TITLE
Doesn't work on OSX 10.10.1 + Chrome 41

### ISSUE THREAD

**Issue by voltrevo** [richtr/NoSleep.js#2] opened 2015-05-03 10:38 UTC
Steps to reproduce
1. Settings -> Energy Saver -> Turn off display after 1min
2. Go to https://rawgit.com/richtr/NoSleep.js/master/example.html
3. Click button
4. Wait ~1min without interacting with device
5. Display turns off

**Comment by richtr** [comment] 2015-05-04 21:05
Currently no code is run on OSX 10.10 since the library does not attempt to match any desktop browser user agent strings. 

NoSleep.js is currently configured to run on iOS (8.2+) and Android devices.

It may be possible to keep the screen alive on desktop browsers with this library. I would need to investigate that further.

**Comment by richtr** [comment] 2017-07-04 22:53
Duplicate of https://github.com/richtr/NoSleep.js/issues/28.

**Closed by richtr** 2017-07-04 22:53 UTC
